config/routes.rb
Rails.application.routes.draw do
     get'users/index',to: 'users#index'
    get 'top/main'
    post 'top/login'
    root 'top#main'
    get 'top/logout'
    get 'users/new',to: 'users#new'
    post 'users', to: 'users#create'
    delete 'users/:id',to: 'users#destroy'
    resources :users,only: [:index,:new,:create,:destroy]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
      if session[:login_uid]
        render :main
      else
        render :login
      end
    end
    
    
    def login
      user = User.find_by(uid: params[:uid])
      if BCrypt::Password.new(user.pass) == params[:pass]
        session[:login_uid] = params[:uid]
        redirect_to root_path
      else
        render :error
      end
    end
    
    def logout
      session.delete(:login_uid)
      redirect_to'/'
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  def create
    user = User.new(uid: params[:user][:uid], pass:
    params[:user][:pass])
    user.pass = BCrypt::Password.create(params[:user][:pass])
    user.save
    
    redirect_to '/' 
  end
  
  def destroy
   render plain: params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/top/error.html.erb
ログイン失敗
<%=link_to '戻る','/'%>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
<%= label_tag :uid, 'ユーザーID' %>
<%= text_field_tag :uid %>
<%= label_tag :pass, 'パスワード' %>
<%= password_field_tag :pass %>
<%= submit_tag 'ログイン' %>
<% end %>
<p><%= link_to '新規登録', '/users/new' %></p>
<p><%= link_to 'ログインID一覧', '/users/index' %></p>

app/views/top/main.html.erb
ログイン中です
<p><%= link_to 'ログインID一覧', '/users/index' %></p>
<%= link_to 'ログアウト',top_logout_path %>

app/views/users/index.html.erb
<% @users.each do |use| %>
<p><%= use.uid %>
<%= link_to '削除', "/users/#{use.id}", method: :delete %>
</p>
<% end %>
<%=link_to '戻る','/'%>

app/views/users/new.html.erb
<%= form_for @user , url: {action: :create} do |f| %>
<%= f.label :uid, 'ID' %>
<%= f.text_field :uid %>
<%= f.label :pass, 'パスワード' %>
<%= f.text_field :pass %>
<%= f.submit '登録' %>
<% end %>